### ISSUE TITLE
Crash while export

### ISSUE THREAD

**Issue by lbaomyscoopapp** [NextLevel/NextLevelSessionExporter#18]
Sometime my app crash in file NextLevelSessionExporter.swift - Line 429
*** -[AVAssetWriterInput appendSampleBuffer:] Cannot append sample buffer: Must start a session (using -[AVAssetWriter startSessionAtSourceTime:) first

They happens rarely and hard to reproduce, but any thoughts why this happens? Thanks

**Comment by piemonte** [comment]
Please use `0.4.3`
