### ISSUE TITLE
Exported Video output green with audio

### ISSUE THREAD

**Issue by delta98** [NextLevel/NextLevelSessionExporter#2]
I've attached the code used to setup the video configuration, any help would be appreciated.
````
let encoder = NextLevelSessionExporter(withAsset: asset)
                        encoder.delegate = self
                        encoder.outputFileType = AVFileTypeMPEG4
                        encoder.optimizeForNetworkUse = true

                        let tmpURL = try! URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
                                .appendingPathComponent(ProcessInfo().globallyUniqueString)
                                .appendingPathExtension("mp4")

                        encoder.outputURL = tmpURL
                        encoder.videoOutputConfiguration = [
                            AVVideoCodecKey: AVVideoCodecH264,
                            AVVideoHeightKey: CGFloat(640),
                            AVVideoWidthKey: CGFloat(352),
                            AVVideoScalingModeKey: AVVideoScalingModeResizeAspectFill,
                            AVVideoCompressionPropertiesKey: [
                                AVVideoAverageBitRateKey: CGFloat(960*1000),
                                AVVideoMaxKeyFrameIntervalKey: CGFloat(30)
                            ]
                        ]
                        encoder.audioOutputConfiguration = [
                            AVFormatIDKey: Int(kAudioFormatMPEG4AAC),
                            AVEncoderBitRateKey: 40000,
                            AVNumberOfChannelsKey: 1,
                            AVSampleRateKey: 16000
                        ]
````

**Comment by piemonte** [comment]
thanks @delta98 ✌️i'll look into it

**Comment by piemonte** [comment]
@delta98 i've noticed when creating these configuration dictionaries, it's important to wrap the numerical values in an NSNumber.

**Comment by patrickbdev** [comment]
@delta98 can you confirm if you were able to resolve this? Getting the same problem even after wrapping in NSNumber(value: ... )

**Comment by piemonte** [comment]
hey gents, apologies, i was able to reproduce this and it looks like a configuration problem with `AVAssetWriterInputPixelBufferAdaptor`. will land a fix when i can narrow it down to the specific key it's missing or expecting in another format.

**Comment by delta98** [comment]
Hi @piemonte any update with this?

**Comment by piemonte** [comment]
@delta98 haven't determined what's causing it. i can verify a valid frame going into the adapter but then the output from the adapter is the green frame. All configurations for the adapter have little or no change. So my guess is that it's either lacking a specific config value that's causing the output frame to be all zeros or something else.

**Comment by piemonte** [comment]
https://github.com/NextLevel/NextLevelSessionExporter/blob/0.0.2/Sources/NextLevelSessionExporter.swift#L402

**Comment by delta98** [comment]
@piemonte we've seen the same, that right up to the point of export, it's receiving the frames, but video comes out green, whilst audio is intact.

**Comment by piemonte** [comment]
commit 4413e0a8baef39d21d3f76932b00ef3ec4a07999
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Mon Jan 16 21:16:27 2017 -0800

    NextLevelSessionExporter, use the resulting computed matrix and transform

commit 73cf0edf7b22467301d81d1ff920d2a651f8c737
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Mon Jan 16 20:49:48 2017 -0800

    NextLevelSessionExporter, use the proper pixel format type

**Comment by delta98** [comment]
@piemonte any luck? Still outputting screen, encoding.

**Comment by piemonte** [comment]
hey @delta98 i haven't had the chance recently because i've been super busy. i'm really curious what's causing this too!! i'll get back to it some point soon, i rely this component for a few things.

**Comment by zeeshansuleman** [comment]
hey @piemonte any update on this issue ?

**Comment by piemonte** [comment]
hey @zeeshansuleman haven't had the chance to investigate. let me know if you uncover the cause.

**Comment by seawolf86** [comment]
hey I have the same problem any update on this issue ?

**Comment by zeeshansuleman** [comment]
hey i have created my own classes after having so much problems in existing libraries.you can view it here. thanks
https://github.com/zeeshansuleman/VideoCompressor.git

**Comment by eddieespinal** [comment]
If anyone else is having issues with this I was able to resolve it in Swift 4 doing the following.  I'm going to fork this repo to my own channel and will submit a PR just in case.  But try this in the meantime.

Change the following code in line 279:

From:

```
pixelBufferAttrib[kCVPixelBufferPixelFormatTypeKey as String] = NSNumber(integerLiteral: Int(kCVPixelFormatType_32BGRA
```

To: 

```
pixelBufferAttrib[kCVPixelBufferPixelFormatTypeKey as String] = NSNumber(integerLiteral: Int(kCVPixelFormatType_32RGBA))
```

I also added some codes after the following line of code in line 487 :
`var transform = videoTrack.preferredTransform`

Add this code after the code above:

```
let rect = CGRect(x: 0, y: 0, width: naturalSize.width, height: naturalSize.height)
                let transformedRect = rect.applying(transform)
                // transformedRect should have origin at 0 if correct; otherwise add offset to correct it
                transform.tx -= transformedRect.origin.x;
                transform.ty -= transformedRect.origin.y;
```

Doing that, I was able to get the results I was looking for while compressing my videos to match what the Whatsapp app is doing.

I hope this helps you save a crazy amount of time researching and trial and errors as I did.
Let me know if you have any questions about this implementation.

Thanks for this great library!

**Comment by eddieespinal** [comment]
Forgot to include how I'm calling the library, which might be also helpful for you guys:

```
let encoder = NextLevelSessionExporter(withAsset: asset)
            encoder.delegate = self
            encoder.outputFileType = AVFileType.mp4.rawValue
            encoder.optimizeForNetworkUse = true
            
            let tmpURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
                .appendingPathComponent(ProcessInfo().globallyUniqueString)
                .appendingPathExtension("mp4")
            encoder.outputURL = tmpURL
            
            let compressionDict: [String: Any] = [
                AVVideoAverageBitRateKey: NSNumber(integerLiteral: 1000000),
                AVVideoProfileLevelKey: AVVideoProfileLevelH264Baseline31
            ]
            encoder.videoOutputConfiguration = [
                AVVideoCodecKey: AVVideoCodecH264,
                
                AVVideoWidthKey: NSNumber(integerLiteral: 480),
                AVVideoHeightKey: NSNumber(integerLiteral: 848),
                AVVideoScalingModeKey: AVVideoScalingModeResizeAspectFill,
                AVVideoCompressionPropertiesKey: compressionDict
            ]
            encoder.audioOutputConfiguration = [
                AVFormatIDKey: kAudioFormatMPEG4AAC,
                AVEncoderBitRateKey: NSNumber(integerLiteral: 96000),
                AVNumberOfChannelsKey: NSNumber(integerLiteral: 2),
                AVSampleRateKey: NSNumber(value: Float(44100))
            ]
            
            do {
                try encoder.export(withCompletionHandler: { () in
                    switch encoder.status {
                    case .completed:
                        print("video export completed")
                        break
                    case .cancelled:
                        print("video export cancelled")
                        break
                    default:
                        break
                    }
                    
                    completionHandler(encoder.outputURL)
                })
            } catch {
                print("failed to export")
            }
```

**Comment by piemonte** [comment]
📎 https://github.com/NextLevel/NextLevelSessionExporter/pull/5

RBGA vs BGRA
