### ISSUE TITLE
NextLevelSessionExporter, did not complete

### ISSUE THREAD

**Issue by andrewfashion** [NextLevel/NextLevelSessionExporter#22]
Even using the default project, it will not export, I just keep getting:

"NextLevelSessionExporter, did not complete"

I'm on the new Xcode 11 using Mojave 10.14.6

**Comment by piemonte** [comment]
hey @andrewfashion if you use the 0.3.0 release as a workaround, will check into this

**Comment by piemonte** [comment]
commit 301baa2b3f5c4fe82c466325debfa0cdc049941f (HEAD -> master)
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Wed Sep 25 15:10:44 2019 -0700

    add status to debug message

commit c920e2257ec8ddd02d2d13ab147a0b306e747339
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Wed Sep 25 15:10:33 2019 -0700

    update project schema

commit e15ee09ab846c760131231998585edf0d6518973
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Wed Sep 25 15:10:18 2019 -0700

    SessionExporter, fix an issue where execution continues after failure

**Comment by andrewfashion** [comment]
Thanks @piemonte ! Did your latest commits just now fix these issues?

**Comment by andrewfashion** [comment]
Hey @piemonte , downgraded to 0.3.0, and I'm still getting a SIGABRT crash on the asset.nextlevel_export line :( any ideas?

`let asset = AVMutableComposition(url: url)

        let tmpURL = URL(fileURLWithPath: NSTemporaryDirectory(), isDirectory: true)
            .appendingPathComponent(ProcessInfo().globallyUniqueString)
            .appendingPathExtension("mp4")
        
        //        exporter.outputURL = tmpURL
        
        let compressionDict: [String: Any] = [
            AVVideoAverageBitRateKey: NSNumber(integerLiteral: 2500000), //lower it if you wish
            AVVideoProfileLevelKey: AVVideoProfileLevelH264BaselineAutoLevel as String,
        ]
        
        let videoOutputConfiguration = [
            AVVideoCodecKey : AVVideoCodecType.h264,
            AVVideoWidthKey : NSNumber(integerLiteral: 1280),
            AVVideoHeightKey: NSNumber(integerLiteral: 720),
            AVVideoScalingModeKey: AVVideoScalingModeResizeAspectFill,
            AVVideoCompressionPropertiesKey: compressionDict
            ] as [String : Any]
        
        let audioOutputConfiguration = [
            AVFormatIDKey: kAudioFormatMPEG4AAC,
            AVEncoderBitRateKey: NSNumber(integerLiteral: 128000),
            AVNumberOfChannelsKey: NSNumber(integerLiteral: 2),
            AVSampleRateKey: NSNumber(value: Float(44100))
            ] as [String : Any]
        
        asset.nextlevel_export(outputFileType: .mp4,
                               outputURL: tmpURL,
                               videoOutputConfiguration: videoOutputConfiguration,
                               audioOutputConfiguration: audioOutputConfiguration,
                               progressHandler: { progress in
                                
            print(progress)
                                
        }) { status in
            switch status {
            case .completed:
                print("completed")
                completionHandler(tmpURL, nil)
                
            case .failed:
                print("failed")
                completionHandler(nil, DareError.unknownError)
                
            default:
                break
            }
        }`

**Comment by andrewfashion** [comment]
Any help is greatly appreciated @piemonte :)

**Comment by piemonte** [comment]
64f9642e3235f44c316d1bbeb22f87c7c0fc6025
