### ISSUE TITLE
Difference between NextLevelSessionExporter and NextLevel capture encoding

### ISSUE THREAD

**Issue by rcfrias** [NextLevel/NextLevelSessionExporter#27]
Hi, its unclear to me what is the advantage of using NextLevelSessionExporter, when the NextLevel capture lib already has encoding settings.  Is this just for the case that we were not using capture?, like if we already have the media and we would only pick it from our median and export it?

**Comment by piemonte** [comment]
hi @rcfrias. you are correct, if you need a library to do audio or video conversions then you can use the exporter. next level lets you capture at various formats in real-time.
