### ISSUE TITLE
Disposing correctly

### ISSUE THREAD

**Issue by febg11** [NextLevel/NextLevelSessionExporter#29]
Hi 
I have managed to use your library to compress some videos... its working really well so thanks for the great library. I have a few of questions if you dont mind answering them. 

1) I haven't done much swift and don't have a great understanding of its garbage collection. Do we have to dispose or clear anything once the encoder has finished? 

2) In the completion handler I noticed that result has a success/failure. Both of which has a (enum?.. im not really sure what it is) .cancelled... When i manually cancel the request using ```exporter.cancelExport()``` it always goes in the switch in the .falure. Under what scenario would it go in the .sucess switch?

```
completionHandler: { result in
            print("Hello IT HAS FINISHED")
            switch result {
                case .success(let status):
                    switch status {
                    case .completed:

                        break
                    case .cancelled:
                        print("User cancelled request ")
                        break
                    default:
              
                        break
                    }
                    break
                
                case .failure(let error as NextLevelSessionExporterError):
                    switch error {
                    case .cancelled:
                        print("User cancelled request ")
                        break
                    default:
                        break
                       
                }
                case .failure(let error):
                         break

```
3) Does this use an MPEG LA patented algorithms and I am ok with using this in a commercial application?

Thanks a lot :)

**Comment by febg11** [comment]
Also Is there any way to know whether the failure was the result of something crashing or the result of calling exporter.cancelExport() as they both seem to get reported as .error .cancelled... e.g. 

```
     case .failure(let error as NextLevelSessionExporterError):
                    switch error {
                    case .cancelled:
```

Im finding it hard to know when the user cancelled vs something crashing

**Comment by febg11** [comment]
Also it seems to give Success.complreted when running on an Iphone se but the came code gives a failure .cancelled when running on iphone 11 pro max.

**Comment by piemonte** [comment]
hey @febg11 thanks for the project interest.

when the cancelled error is returned, it's always user initiated and not treated as a `success`.

this library is a wrapper around `AVAudioSessionExporter` in `AVFoundation`, so you'll have to refer to it's licensing guidelines and commercial use.

it is possible for some devices to not support the same encoding capabilities as others, you will have to check for specific encoding support and why completion status could be different. can't help without details.

**Comment by febg11** [comment]
ah ok  thanks for answering my questions :) 

Is there anyway to check whether the resulting output file has not compressed correctly, such as if it is corrupt? Rather than having to rely on the completion status (sorry if this is a simple thing I have only been using swift for like a week and a half)
