### ISSUE TITLE
Can I export audio only from a mp4

### ISSUE THREAD

**Issue by slash7** [NextLevel/NextLevelSessionExporter#3]
Hi @piemonte ,

Can NextLevelSessionExporter be used to export only the audio from a video asset ?
Specifically, I'm looking to export the audio tracks of a mp4 file to CoreAudio format.

Thanks

**Comment by piemonte** [comment]
hey @slash7 i haven't experimented with audio-only use cases to give you the exact steps or answer. i'm sure it could work after setting the appropriate output filetype.

**Comment by slash7** [comment]
Hi @piemonte,

Thanks for answering,  after testing I saw that  once the .mp4 is recorded it can only be exported to audio in the format .m4a. The core audio format (.caf) is not available, so I'm forced to capture the video and audio separately.
