### ISSUE TITLE
Problem with output format

### ISSUE THREAD

**Issue by capitan91** [NextLevel/NextLevelSessionExporter#8]
Hi,
I’m experiencing some problem with differents video resolutions during the exporting process.
Could you please explain me if on iOS only certain resolutions are supported or if is this a library bug?

Thanks in advance.

**Comment by piemonte** [comment]
hey @capitan91, you can ask a device what it supports like this:

```Swift
    AVAssetExportSession.allExportPresets()
```

If you have specific presets, then you can check if they are compatible like this:

```Swift
   AVAssetExportSession.exportPresets(compatibleWith asset: AVAsset) -> [String]
```

📎 https://developer.apple.com/documentation/avfoundation/avassetexportsession/1390567-exportpresets
